/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OpenfoodfactsAttributionRouteImport } from './routes/openfoodfacts-attribution'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CookRouteImport } from './routes/cook'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminShopRouteImport } from './routes/admin/shop'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminQueueRouteImport } from './routes/admin/queue'
import { Route as AdminPopupsRouteImport } from './routes/admin/popups'
import { Route as AdminPlansRouteImport } from './routes/admin/plans'
import { Route as AdminOffersRouteImport } from './routes/admin/offers'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminAdsRouteImport } from './routes/admin/ads'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenfoodfactsAttributionRoute =
  OpenfoodfactsAttributionRouteImport.update({
    id: '/openfoodfacts-attribution',
    path: '/openfoodfacts-attribution',
    getParentRoute: () => rootRouteImport,
  } as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CookRoute = CookRouteImport.update({
  id: '/cook',
  path: '/cook',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShopRoute = AdminShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQueueRoute = AdminQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPopupsRoute = AdminPopupsRouteImport.update({
  id: '/popups',
  path: '/popups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOffersRoute = AdminOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cook': typeof CookRoute
  '/cookies': typeof CookiesRoute
  '/impressum': typeof ImpressumRoute
  '/inventory': typeof InventoryRoute
  '/openfoodfacts-attribution': typeof OpenfoodfactsAttributionRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/shopping': typeof ShoppingRoute
  '/terms': typeof TermsRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/popups': typeof AdminPopupsRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shop': typeof AdminShopRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cook': typeof CookRoute
  '/cookies': typeof CookiesRoute
  '/impressum': typeof ImpressumRoute
  '/inventory': typeof InventoryRoute
  '/openfoodfacts-attribution': typeof OpenfoodfactsAttributionRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/shopping': typeof ShoppingRoute
  '/terms': typeof TermsRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/popups': typeof AdminPopupsRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shop': typeof AdminShopRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cook': typeof CookRoute
  '/cookies': typeof CookiesRoute
  '/impressum': typeof ImpressumRoute
  '/inventory': typeof InventoryRoute
  '/openfoodfacts-attribution': typeof OpenfoodfactsAttributionRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/shopping': typeof ShoppingRoute
  '/terms': typeof TermsRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/offers': typeof AdminOffersRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/popups': typeof AdminPopupsRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shop': typeof AdminShopRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cook'
    | '/cookies'
    | '/impressum'
    | '/inventory'
    | '/openfoodfacts-attribution'
    | '/privacy'
    | '/settings'
    | '/shopping'
    | '/terms'
    | '/admin/ads'
    | '/admin/audit'
    | '/admin/offers'
    | '/admin/plans'
    | '/admin/popups'
    | '/admin/queue'
    | '/admin/settings'
    | '/admin/shop'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cook'
    | '/cookies'
    | '/impressum'
    | '/inventory'
    | '/openfoodfacts-attribution'
    | '/privacy'
    | '/settings'
    | '/shopping'
    | '/terms'
    | '/admin/ads'
    | '/admin/audit'
    | '/admin/offers'
    | '/admin/plans'
    | '/admin/popups'
    | '/admin/queue'
    | '/admin/settings'
    | '/admin/shop'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cook'
    | '/cookies'
    | '/impressum'
    | '/inventory'
    | '/openfoodfacts-attribution'
    | '/privacy'
    | '/settings'
    | '/shopping'
    | '/terms'
    | '/admin/ads'
    | '/admin/audit'
    | '/admin/offers'
    | '/admin/plans'
    | '/admin/popups'
    | '/admin/queue'
    | '/admin/settings'
    | '/admin/shop'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CookRoute: typeof CookRoute
  CookiesRoute: typeof CookiesRoute
  ImpressumRoute: typeof ImpressumRoute
  InventoryRoute: typeof InventoryRoute
  OpenfoodfactsAttributionRoute: typeof OpenfoodfactsAttributionRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  ShoppingRoute: typeof ShoppingRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openfoodfacts-attribution': {
      id: '/openfoodfacts-attribution'
      path: '/openfoodfacts-attribution'
      fullPath: '/openfoodfacts-attribution'
      preLoaderRoute: typeof OpenfoodfactsAttributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cook': {
      id: '/cook'
      path: '/cook'
      fullPath: '/cook'
      preLoaderRoute: typeof CookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shop': {
      id: '/admin/shop'
      path: '/shop'
      fullPath: '/admin/shop'
      preLoaderRoute: typeof AdminShopRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/queue': {
      id: '/admin/queue'
      path: '/queue'
      fullPath: '/admin/queue'
      preLoaderRoute: typeof AdminQueueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/popups': {
      id: '/admin/popups'
      path: '/popups'
      fullPath: '/admin/popups'
      preLoaderRoute: typeof AdminPopupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/offers': {
      id: '/admin/offers'
      path: '/offers'
      fullPath: '/admin/offers'
      preLoaderRoute: typeof AdminOffersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdsRoute: typeof AdminAdsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminOffersRoute: typeof AdminOffersRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminPopupsRoute: typeof AdminPopupsRoute
  AdminQueueRoute: typeof AdminQueueRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminShopRoute: typeof AdminShopRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdsRoute: AdminAdsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminOffersRoute: AdminOffersRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminPopupsRoute: AdminPopupsRoute,
  AdminQueueRoute: AdminQueueRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminShopRoute: AdminShopRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CookRoute: CookRoute,
  CookiesRoute: CookiesRoute,
  ImpressumRoute: ImpressumRoute,
  InventoryRoute: InventoryRoute,
  OpenfoodfactsAttributionRoute: OpenfoodfactsAttributionRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  ShoppingRoute: ShoppingRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
