-- ============================================================
-- dev_grant_admin was REMOVED for security.
-- It allowed anonymous users to self-grant admin. Admin access
-- is now set via raw_app_meta_data directly, and dev/preview
-- testing uses the localhost route-guard bypass.
-- ============================================================
